# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_pos', to='cms.Pos'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_term', to='cms.Term'),
        ),
        migrations.AlterField(
            model_name='score',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_term', to='cms.Term'),
        ),
        migrations.AlterField(
            model_name='score',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_title', to='cms.Title'),
        ),
    ]
