# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_term_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_num_of_letter', models.IntegerField(verbose_name='\u30c7\u30fc\u30bf\u6570\uff08\u6587\u5b57/\u65e5\uff09')),
                ('daily_num_of_title', models.IntegerField(verbose_name='\u30c7\u30fc\u30bf\u6570\uff08\u30bf\u30a4\u30c8\u30eb/\u65e5\uff09')),
                ('total_num_of_letter', models.IntegerField(verbose_name='\u7d2f\u8a08\u30c7\u30fc\u30bf\u6570\uff08\u6587\u5b57\uff09')),
                ('total_num_of_title', models.IntegerField(verbose_name='\u7d2f\u8a08\u30c7\u30fc\u30bf\u6570\uff08\u30bf\u30a4\u30c8\u30eb\uff09')),
                ('date', models.DateTimeField(verbose_name='\u53ce\u96c6\u65e5\u6642')),
            ],
        ),
    ]
